# Generated by Django 3.2.13 on 2022-04-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_shoppingcart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
