# Generated by Django 3.2.13 on 2022-04-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_shoppingcart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='total',
            field=models.FloatField(),
        ),
    ]
