# Generated by Django 3.2.13 on 2022-04-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_shoppingcart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='total',
        ),
    ]
