# Generated by Django 3.2.13 on 2022-04-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220425_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartproducts',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
