# Generated by Django 3.2.13 on 2022-04-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_shoppingcartproducts_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='cart',
        ),
    ]
