# Generated by Django 3.2.13 on 2022-04-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220426_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(default='https://www.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png'),
        ),
    ]
