# Generated by Django 3.2.13 on 2022-04-27 08:03

import django.core.validators
from django.db import migrations, models
import projectshop.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_profile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.MinLengthValidator(2), projectshop.main.validators.only_letters_validator]),
        ),
    ]
