# Generated by Django 3.2.13 on 2022-04-27 08:51

import django.core.validators
from django.db import migrations, models
import projectshop.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), projectshop.main.validators.only_letters_validator]),
        ),
    ]
