# Generated by Django 3.2.13 on 2022-04-27 11:46

from django.db import migrations, models
import projectshop.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=10, validators=[projectshop.main.validators.only_numbers]),
        ),
    ]
