# Generated by Django 3.2.13 on 2022-04-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartproducts',
            name='product_total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
