# Generated by Django 3.2.13 on 2022-04-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_shoppingcartproducts_product_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartproducts',
            name='product_total',
        ),
    ]
